services:
  - type: web
    name: flipkart-clone
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "node server.js"
    envVars:
      - key: CASHFREE_CLIENT_ID
        value: 114321026a5f66183345bd82ee50123411
      - key: CASHFREE_CLIENT_SECRET
        value: cfsk_ma_prod_4fed9c52cb45cf5972e9a3b11e7bacde_d081651e
